### ISSUE TITLE
USB gaming support?

### ISSUE THREAD

**Issue by spielvan** [revvv/Nintendont-XBOX360#16] opened 2023-06-13 17:32 UTC
@revvv first of all thank you for the great port with support from the nintendont xbox 360 controller, for me it's perfect, the only thing missing would be the support for games via usb which already happens in the official nintendont version of bro FIX94, is it possible would it be possible to put this support on it? a hug and all the best always.

**Comment by revvv** [comment] 2023-06-14 07:52
Well, nice to hear that, thank you. Unfortunately I have bad news for you:
This is a duplicate of #4

**Closed as completed by revvv** 2023-06-14 07:52 UTC
