### ISSUE TITLE
USB FAT device could not be opened

### ISSUE THREAD

**Issue by PedroRafael215** [revvv/Nintendont-XBOX360#14] opened 2023-01-23 23:56 UTC
i cant load games from usb. It shows "USB FAT device could not be opened" in red at the top of screen.
Any hints?

**Comment by felipecbritto** [comment] 2023-01-27 04:04
Same here.

**Comment by PedroRafael215** [comment] 2023-01-27 11:53
At least booting from disk is possible.Playing burned dvd works.  
I'm wondering to buy a new sd card just to test if it loads from sd too.
I wonder why original build of Nintendont don't see this project and implement it there.
I was really amazed to see my usb xbox360 controller working on it.

**Comment by felipecbritto** [comment] 2023-01-27 12:14
SD works fine.

**Comment by revvv** [comment] 2023-03-25 13:53
Sorry for my late answer, but github does not always send me an e-mail.

Unfortunately this is not fixable. Duplicate of #4

**Closed as completed** 2023-03-25 13:55 UTC
