### ISSUE TITLE
Is third party xbox 360 controller VOYEE compatible?

### ISSUE THREAD

**Issue by Sebgames** [revvv/Nintendont-XBOX360#17] opened 2023-08-16 21:24 UTC
I had previously asked this question, but it was canceled due to inactivity.
when trying retrodetest it does not recognize it but when disconnecting and connecting I managed to get it to be recognized halfway but it only identifies the large button in the middle and when testing rumble or next led the screen freezes

**Comment by revvv** [comment] 2023-08-17 11:04
Well, then your controller is not really a clone and is not supported. Duplicate of #15

**Closed as completed** 2023-08-17 11:05 UTC

**Comment by Sebgames** [comment] 2023-08-17 14:15
and there is no way to make it work with some modification or adapter or something like that

**Comment by revvv** [comment] 2023-08-21 08:17
No
